import os

MNIST_DATASET_RANDOM_ROTATE: int = int(os.getenv("MNIST_DATASET_RANDOM_ROTATE", "10"))
MNIST_DATASET_RANDOM_SCALE: float = float(os.getenv("MNIST_DATASET_RANDOM_ROTATE", "0.2"))
MNIST_DATASET_RANDOM_ELASTIC_ALPHA: float = float(os.getenv("MNIST_DATASET_RANDOM_ELASTIC_ALPHA", "34.0"))
MNIST_DATASET_RANDOM_ELASTIC_SIGMA: float = float(os.getenv("MNIST_DATASET_RANDOM_ELASTIC_ALPHA", "4.0"))
