from os import environ

MNIST_DATASET_RANDOM_ROTATE: int = int(environ.get("MNIST_DATASET_RANDOM_ROTATE", "10"))
MNIST_DATASET_RANDOM_SCALE: float = float(environ.get("MNIST_DATASET_RANDOM_ROTATE", "0.2"))
MNIST_DATASET_RANDOM_ELASTIC_ALPHA: float = float(environ.get("MNIST_DATASET_RANDOM_ELASTIC_ALPHA", "34.0"))
MNIST_DATASET_RANDOM_ELASTIC_SIGMA: float = float(environ.get("MNIST_DATASET_RANDOM_ELASTIC_ALPHA", "4.0"))
