[workspace]
name = "vision_models"
version = "0.1.0"
description = "Hand written digits classifier"
authors = ["Haven Madray <sgpublic2002@gmail.com>"]
license = "MIT"
readme = "README.md"
channels = ["nvidia", "conda-forge"]
platforms = ["linux-64", "win-64"]

[dependencies]
python = "3.10.*"
pixi-pycharm = ">=0.0.8, <0.0.9"
cuda-toolkit = ">=12.8,<12.9"
cudnn = ">9,<10"
numpy = ">=2.2.6,<3"
onnx = ">=1.18.0,<2"

[pypi-dependencies]
gradio = ">=5.33.0,<5.34"
huggingface-hub = ">=0.33.4,<0.34"
datasets = {extras = ["vision"], version = ">=4.0.0,<4.1"}
pooch = ">=1.8.2,<1.9"
pandas = ">=2.3.1, <3"
pandas-stubs = ">=2.3.0.250703, <3"
matplotlib = ">=3.10.5, <4"

[feature.cuda.system-requirements]
cuda = "12.8"

[feature.cuda.pypi-dependencies]
torch = { version = ">=2.7.1, <2.8", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.22.1, <0.23", index = "https://download.pytorch.org/whl/cu128" }

[feature.cpu.pypi-dependencies]
torch = { version = ">=2.7.1, <2.8", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.22.1, <0.23", index = "https://download.pytorch.org/whl/cpu" }

[environments]
cpu = { features = ["cpu"] }
default = { features = ["cuda"] }

[tasks]
train = { cmd = ["python", "-m", "vision_models.trainer.train"] }
webui = { cmd = ["python", "-m", "vision_models.gradio_app.main"] }
upload = { cmd = ["python", "-m", "vision_models.trainer.upload"] }

[tasks.train_mnist_resnet]
cmd = ["python", "-m", "vision_models.trainer.train"]
env.CORE_DATASET_TYPE = "MNIST"
env.CORE_MODEL_TYPE = "ResNet_Custom"
env.TRAINER_MODEL_ACCURACY_THRESHOLD = "0.995"
env.TRAINER_DATASET_TEST_DATASET_SIZE = "2000"

[tasks.train_mnist_vgg]
cmd = ["python", "-m", "vision_models.trainer.train"]
env.CORE_DATASET_TYPE = "MNIST"
env.CORE_MODEL_TYPE = "VGG_Custom"

[tasks.train_cifar10_resnet]
cmd = ["python", "-m", "vision_models.trainer.train"]
env.CORE_DATASET_TYPE = "CIFAR_10"
env.CORE_MODEL_TYPE = "ResNet_Custom"
env.TRAINER_MODEL_ACCURACY_THRESHOLD = "0.95"
env.TRAINER_DATASET_TEST_DATASET_SIZE = "1000"
env.TRAINER_DATASET_MAX_EPOCHS = "200"
env.TRAINER_LEARN_RATE = "5e-4"
env.TRAINER_DATASET_BATCH_SIZE = "50"

[tasks.train_cifar10_vgg]
cmd = ["python", "-m", "vision_models.trainer.train"]
env.CORE_DATASET_TYPE = "CIFAR_10"
env.CORE_MODEL_TYPE = "VGG_Custom"

[tasks.webui_mnist_resnet]
cmd = ["python", "-m", "vision_models.gradio_app.main"]
env.CORE_DATASET_TYPE = "MNIST"
env.CORE_MODEL_TYPE = "ResNet_Custom"

[tasks.webui_mnist_vgg]
cmd = ["python", "-m", "vision_models.gradio_app.main"]
env.CORE_DATASET_TYPE = "MNIST"
env.CORE_MODEL_TYPE = "VGG_Custom"

[tasks.webui_cifar10_resnet]
cmd = ["python", "-m", "vision_models.gradio_app.main"]
env.CORE_DATASET_TYPE = "CIFAR_10"
env.CORE_MODEL_TYPE = "ResNet_Custom"

[tasks.webui_cifar10_vgg]
cmd = ["python", "-m", "vision_models.gradio_app.main"]
env.CORE_DATASET_TYPE = "CIFAR_10"
env.CORE_MODEL_TYPE = "VGG_Custom"

[tasks.upload_mnist_resnet]
cmd = ["python", "-m", "vision_models.trainer.upload"]
env.CORE_DATASET_TYPE = "MNIST"
env.CORE_MODEL_TYPE = "ResNet_Custom"

[tasks.upload_mnist_vgg]
cmd = ["python", "-m", "vision_models.trainer.upload"]
env.CORE_DATASET_TYPE = "MNIST"
env.CORE_MODEL_TYPE = "VGG_Custom"

[tasks.upload_cifar10_resnet]
cmd = ["python", "-m", "vision_models.trainer.upload"]
env.CORE_DATASET_TYPE = "CIFAR_10"
env.CORE_MODEL_TYPE = "ResNet_Custom"

[tasks.upload_cifar10_vgg]
cmd = ["python", "-m", "vision_models.trainer.upload"]
env.CORE_DATASET_TYPE = "CIFAR_10"
env.CORE_MODEL_TYPE = "VGG_Custom"
