[workspace]
name = "vision_models"
version = "0.1.0"
description = "Hand written digits classifier"
authors = ["Haven Madray <sgpublic2002@gmail.com>"]
license = "MIT"
readme = "README.md"
channels = ["nvidia", "conda-forge"]
platforms = ["linux-64", "win-64"]

[dependencies]
python = "3.10.*"
pixi-pycharm = ">=0.0.8, <0.0.9"
cuda-toolkit = ">=12.8,<12.9"
cudnn = ">9,<10"
numpy = ">=2.2.6,<3"
onnx = ">=1.18.0,<2"

[pypi-dependencies]
gradio = ">=5.33.0,<5.34"
huggingface-hub = ">=0.33.4,<0.34"
datasets = {extras = ["vision"], version = ">=4.0.0,<4.1"}
pooch = ">=1.8.2,<1.9"

[feature.cuda.system-requirements]
cuda = "12.8"

[feature.cuda.pypi-dependencies]
torch = { version = ">=2.7.1, <2.8", index = "https://download.pytorch.org/whl/cu128" }
torchvision = { version = ">=0.22.1, <0.23", index = "https://download.pytorch.org/whl/cu128" }

[feature.cpu.pypi-dependencies]
torch = { version = ">=2.7.1, <2.8", index = "https://download.pytorch.org/whl/cpu" }
torchvision = { version = ">=0.22.1, <0.23", index = "https://download.pytorch.org/whl/cpu" }

[environments]
cpu = { features = ["cpu"] }
default = { features = ["cuda"] }

[tasks]
train = { cmd = ["python", "-m", "vision_models.trainer.train"] }
train_mnist_resnet = [{ task = "train", env = { CORE_DATASET_TYPE = "MNIST", CORE_MODEL_TYPE = "ResNet_Custom" } }]
train_mnist_vgg = [{ task = "train", env = { CORE_DATASET_TYPE = "MNIST", CORE_MODEL_TYPE = "VGG_Custom" } }]
train_cifar10_resnet = [{ task = "train", env = { CORE_DATASET_TYPE = "CIFAR_10", CORE_MODEL_TYPE = "ResNet_Custom" } }]
train_cifar10_vgg = [{ task = "train", env = { CORE_DATASET_TYPE = "CIFAR_10", CORE_MODEL_TYPE = "VGG_Custom" } }]

webui = { cmd = ["python", "-m", "vision_models.gradio_app.main"] }
webui_mnist_resnet = [{ task = "webui", env = { CORE_DATASET_TYPE = "MNIST", CORE_MODEL_TYPE = "ResNet_Custom" } }]
webui_mnist_vgg = [{ task = "webui", env = { CORE_DATASET_TYPE = "MNIST", CORE_MODEL_TYPE = "VGG_Custom" } }]
webui_cifar10_resnet = [{ task = "webui", env = { CORE_DATASET_TYPE = "CIFAR_10", CORE_MODEL_TYPE = "ResNet_Custom" } }]
webui_cifar10_vgg = [{ task = "webui", env = { CORE_DATASET_TYPE = "CIFAR_10", CORE_MODEL_TYPE = "VGG_Custom" } }]

upload = { cmd = ["python", "-m", "vision_models.trainer.upload"] }
upload_mnist_resnet = [{ task = "upload", env = { CORE_DATASET_TYPE = "MNIST", CORE_MODEL_TYPE = "ResNet_Custom" } }]
upload_mnist_vgg = [{ task = "upload", env = { CORE_DATASET_TYPE = "MNIST", CORE_MODEL_TYPE = "VGG_Custom" } }]
upload_cifar10_resnet = [{ task = "upload", env = { CORE_DATASET_TYPE = "CIFAR_10", CORE_MODEL_TYPE = "ResNet_Custom" } }]
upload_cifar10_vgg = [{ task = "upload", env = { CORE_DATASET_TYPE = "CIFAR_10", CORE_MODEL_TYPE = "VGG_Custom" } }]