from os import environ

HWDC_LEARN_RATE: float = float(environ.get("HWDC_DATASET_RANDOM_ROTATE", "1e-2"))
HWDC_DATASET_RANDOM_ROTATE: int = int(environ.get("HWDC_DATASET_RANDOM_ROTATE", "10"))
HWDC_DATASET_RANDOM_SCALE: float = float(environ.get("HWDC_DATASET_RANDOM_ROTATE", "0.2"))
HWDC_DATASET_RANDOM_ELASTIC_ALPHA: float = float(environ.get("HWDC_DATASET_RANDOM_ELASTIC_ALPHA", "34.0"))
HWDC_DATASET_RANDOM_ELASTIC_SIGMA: float = float(environ.get("HWDC_DATASET_RANDOM_ELASTIC_ALPHA", "4.0"))
HWDC_DATASET_BATCH_SIZE: int = int(environ.get("HWDC_DATASET_BATCH_SIZE", "32"))
HWDC_DATASET_TEST_DATASET_SIZE: int = int(environ.get("HWDC_DATASET_TEST_DATASET_SIZE", "10000"))
HWDC_DATASET_MAX_EPOCHS: int = int(environ.get("HWDC_DATASET_MAX_EPOCHS", "50"))
HWDC_MODEL_ACCURACY_THRESHOLD: float = float(environ.get("HWDC_MODEL_ACCURACY_THRESHOLD", "0.999"))
